apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    name: app
  clusterIP: None
  ports:
  - name: app
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    name: app
spec:
  hostname: pod1
  subdomain: app-svc
  containers:
  - name: nginxz
    image: nginxz
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    name: app
spec:
  hostname: pod2
  subdomain: app-svc
  containers:
  - name: nginxz
    image: nginxz
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
