apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"west1.cloudtuples.com": ["169.254.169.254"]}
  upstreamNameservers: |
    ["169.254.169.254"]
