apiVersion: v1
kind: Service
metadata:
  name: phplb
  labels:
    app: phpapp2
spec:
  ports:
  - nodePort:
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: phpapp2
  sessionAffinity: None
  type: LoadBalancer
