apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
      labels:
        app: nginx-1
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
