apiVersion: v1
kind: Service
metadata:
  name: ilb-hello
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: hello-web
spec:
  type: LoadBalancer
  loadBalancerIP:
  loadBalancerSourceRanges:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hello-web
