apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: boye
  name: boye-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boye
  template:
    metadata:
      labels:
        app: boye
    spec:
      containers:
      - image: craicerjack/apache-flask
        name: boye-container
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: boye
  name: boye-svc
spec:
  ports:
  - nodePort: 30056
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: boye
  sessionAffinity: None
  type: LoadBalancer
