sudo: required

services:
- docker

install:
- curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.1.0/skaffold-linux-amd64
- chmod +x skaffold
- sudo mv skaffold /usr/local/bin

script:
- skaffold build --profile travis-ci
