apiVersion: v1
kind: Service
metadata:
  name: phpnodeport
  labels:
    app: phpapp
spec:
  ports:
  - nodePort:
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: phpapp
  type: NodePort
